server:
  port: 8080
#####
spring: 
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/smart
    username: root 
    password: 123456 #3399399 
    driver-class-name: com.mysql.jdbc.Driver 
    
mybatis:  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.king.entity
  configuration:
    map-underscore-to-camel-case: true