server:
  port: 8080
#####
spring: 
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root 
    password: 399399 
    driver-class-name: com.mysql.jdbc.Driver 
    
mybatis:  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.king.entity